# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpl_number', models.CharField(max_length=50)),
                ('pipe_size', models.CharField(max_length=50)),
                ('wall_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weld_number', models.CharField(max_length=50)),
                ('xray_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=50)),
                ('xray_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=50)),
                ('dpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weldTracker.Dpl')),
                ('qc_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_dpl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-xray_completed',),
            },
        ),
    ]
