# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weldTracker', '0002_auto_20170119_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='weldnumber',
            name='weld_notes',
            field=models.TextField(blank=True),
        ),
    ]
